version: '2.2'
services:
    eureka-service:
        image: eureka-server
        environment:
            - SERVER_PORT=8080
        ports:
            - 8081:8080
        networks:
            - mynet
    subscription-postgresql:
        extends:
            file: postgresql.yml
            service: subscription-postgresql
        networks:
            - mynet
    event-service:
        image: event-microservice
        networks:
            - mynet
        environment:
            - SERVER_PORT=8080
    mail-service:
        image: mail-microservice
        networks:
            - mynet
        environment:
            - SERVER_PORT=8080
    subscription-service:
        image: subscription-microservice
        networks:
            - mynet
        ports:
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - SPRING_DATASOURCE_URL=jdbc:postgresql://subscription-postgresql:5432/subscriptiondb
            - EUREKA_INSTANCE_HOSTNAME=eureka-service
networks:
    mynet:
        driver: bridge
